[package]
name = "aoc2019"
version = "0.0.8"
authors = ["Matt Rabitsky <mRabitsky@gmail.com>"]
edition = "2018"

[dependencies]
glob = "^0.3"
itertools = "0.8.2"
minifb = "0.14.0"
ndarray = "0.13.0"
permutohedron = "0.2.4"
petgraph = "^0.4.13"
structopt = "^0.3.5"
